import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/Components/Navbar";
import { Providers } from "./Providers";
import ToastProvider from "@/app/ToastProvider"; // 👈 ToastProvider import किया
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CG Yatri",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Head>
      <link rel="icon" href="/favicon.ico" />
  <link rel="icon" type="image/png" href="/favicon.png" />
        <meta name="google-site-verification" content="hqLTqraixEDvuIrdLX0_PTQN5Z7bNrQQQhWYNBSaXPw" />
        </Head>
      <body>
        <Providers>
          <ToastProvider> 
        <Navbar />
            {children}
          </ToastProvider>
        </Providers>
      </body>
    </html>
  );
}
